env:
    credentials: "ENCRYPTED[!8147cb72c7dd196ab9d3c078e4489d3cea8a9859ee2ce15961856c4ecbcfd3ac6274e381c899122a3540da235c407e31!]"
    rcloneconfig: "ENCRYPTED[!47a1d8ea0882f79f5e2c6924f4378d96e838938603e20a2be68f3e1b435f7152fde4e3871cc2c22860a32029e39b5519!]"
    tokentl: "ENCRYPTED[!72ad07ee7a6a8b34799858263fe0aa3d2922b50005fd57120a6a3afa462ade05cbdd296ccfdf42cf97b614372dbd39e1!]"
    idtl: "ENCRYPTED[!d2b96ef40bc9bfd865ce74298f7306133e2c70f4bef1453c9bb8c958a444d5e2e2c566f824157123a821f795c0929b3a!]"
    lunch: lunch aosqp_juice-userdebug
    make: mka qassa

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Setup Build"
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.rclone.conf
       - git config --global user.name "Lynx"
       - git config --global user.email "rifqikanekii140202@gmail.com"
       - echo "$credentials" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - mkdir -p ~/ccache
       - rclone copy lynx:aosqp/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/
  
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./w.sh
  
  Sync_script:
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start sync Source"
      - mkdir -p ~/rom
      - cd ~/rom
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/lynnnnzx/manifest.git -b Q -g default,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      - git clone https://github.com/lynnnnzx/android_device_xiaomi_juice-q -b qassa device/xiaomi/juice
      - git clone https://github.com/lynnnnzx/android_vendor_xiaomi_juice-q -b 10.staging vendor/xiaomi/juice
      - git clone https://github.com/frstprjkt/kernel_xiaomi_juice-Q -b frost.staging kernel/xiaomi/juice --depth 1
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

  Build_script:
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build Started"
      - ./collect.sh
#      - ./final.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd ~/rom/out/target/product/juice/ && ls AOSQP*.zip) Completed!"

  Upload_script:
#      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading Build $(cd ~/rom/out/target/product/juice/ && ls AOSQP*.zip)"
#      - rclone copy ~/rom/out/target/product/juice/AOSQP*.zip lynx:juice -P
#      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd ~/rom/out/target/product/juice/ && ls AOSQP*.zip) Uploaded Successfully!"
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd ~/
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz lynx:aosqp -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Ccache Uploaded Succesfully"

