task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: 20020214/lynzx:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - DEBIAN_FRONTEND=noninteractive
       - sudo apt install python3 -y
       - sudo ln -sf /usr/bin/python3 /usr/bin/python
       - git config --global user.name "lynnnnzx"
       - git config --global user.email "rifqikanekii140202@gmail.com"
       - mkdir -p /tmp/ccache
       - curl -L -o /tmp/ccache.tar.gz http://anu.inok189.workers.dev/aosp/ccache.tar.gz
       - cd /tmp
       - time tar xf ccache.tar.gz
       - cd /tmp
  
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - cd /tmp/rom
      - rm -rf *
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/SuperiorOS/manifest -b eleven -g default,-device,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      # DT/VT/KT/TC
      - git clone --depth=1 https://github.com/lynnnnzx/device_xiaomi_juice -b superior-juice device/xiaomi/juice
      - git clone --depth=1 https://github.com/lynnnnzx/prebuilt_vendor_juice --single-branch -b A11 vendor/xiaomi/juice
      - git clone --depth=1 https://github.com/lynnnnzx/android_kernel_xiaomi_bengal --single-branch -b test kernel/xiaomi/juice
      - git clone --depth=1 https://gitlab.com/AnggaR96s/clang-gengkapak -b main prebuilts/clang/host/linux-x86/clang-gengkapak
      - echo "============================"
      - echo "Sync Completed!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - ./collect.sh
#      - ./final.sh
      - echo "============================"
      - echo "Build Completed!"
      - echo "============================"

  Upload_script:
      - echo "============================"
      - echo "Uploading the Build...."
      - echo "============================"
#      - curl --upload-file /tmp/rom/out/target/product/juice/SuperiorOS*.zip https://transfer.sh
      - ./ziping.sh
      - cd /tmp
      - curl --upload-file ccache.tar.gz https://transfer.sh
      - echo " "
      - echo "============================"
      - echo "Build Uploaded Successfully!"
      - echo "============================"
