env:
    lunch: lunch aosqp_juice-userdebug
    make: mka qassa

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: inok2341/anu:latest
      cpu: 2
      memory: 8G
        
  Anu_script:
       - export DEBIAN_FRONTEND=noninteractive
       - git config --global user.name "Lynx"
       - git config --global user.email "rifqikanekii140202@gmail.com"
       - cd ~/
       - git clone https://github.com/mvaisakh/gcc-arm64 -b gcc-master gcc
       - ./gcc/bin/aarch64-elf-gcc-13.0.0 --version
       - ./gcc/bin/aarch64-elf-gcc --version
       - ./gcc/bin/aarch64-elf-ld.lld --version
       - ./gcc/bin/aarch64-elf-ld --version
