env:
    anu: "ENCRYPTED[!a333650e875c44dcc422f0bdfeb33e418ff603be43470ee3c6afe6cf553ddf0de06ba1498df523878139003e44d41559!]"

task:
  name: "Import Aosp Clang From Gitlab..."
  timeout_in: 120m
  container:
      image: inok2341/anu:latest
      cpu: 2
      memory: 8G
  
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h

  Clone_script:
      - cd ~/
      - git clone --depth=1 https://gitlab.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r445002.git -b 12.0 clang

  Push_script:
      - cd ~/clang
      - rm -rf .git
      - git init
      - git config --global user.name "lynnnnzx"
      - git config --global user.email "rifqikanekii140202@gmail.com"
      - git add .
      - git checkout -b 12.0
      - git commit -asm "Import clang-r445002 From Crdroid Gitlab"
      - git remote add origin https://github.com/lynnnnzx/prebuilts_clang_host_linux-x86_clang-r445002.git
      - git remote set-url origin https://$anu@github.com/lynnnnzx/prebuilts_clang_host_linux-x86_clang-r445002.git
      - git push origin 12.0 -f
