env:
    anu: "ENCRYPTED[!a333650e875c44dcc422f0bdfeb33e418ff603be43470ee3c6afe6cf553ddf0de06ba1498df523878139003e44d41559!]"
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: 20020214/lynzx:latest
      cpu: 8
      memory: 32G
 
  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - DEBIAN_FRONTEND=noninteractive
       - sudo apt install python3 -y
       - sudo ln -sf /usr/bin/python3 /usr/bin/python
       - git config --global user.name "lynnnnzx"
       - git config --global user.email "rifqikanekii140202@gmail.com"
 
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - cd /tmp/rom
      - git clone https://$anu@github.com/lynnnnzx/tc-build.git

  Build_script:
      - cd /tmp/rom/tc-build
      - chmod +x build-tc.sh
      - ./build-tc.sh
