env:
    rcloneconfig: "ENCRYPTED[2aaa874ed2e5234375fc67c195e7e30c78ce131898eff50f3163102006cf60203fd01e00b040ceb5092a01a771de2024]"
    tokentl: "ENCRYPTED[278f3e180162157a66d5ecdcf54bb8a7189ae0d469d0e95018347b778a634ca8f6903a67407b27ff64ad5ca4b75a679d]"
    idtl: "ENCRYPTED[beb537072d749513bc64623e6c14b5dc34c182690c1fcff3884147aa135b64128f872e55f789dd816d7595e38b92de09]"
    build: "ENCRYPTED[!8576e62ae3b4c48e3f56bcec974a8de92b5163e6fff553d6686f946b3c614ee493277b36576777913d45aec0311da91e!]"

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: 20020214/lynzx:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.config/rclone/rclone.conf
       - DEBIAN_FRONTEND=noninteractive
       - sudo apt install python3 -y
       - sudo ln -sf /usr/bin/python3 /usr/bin/python

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h

  Build-Kernel_script:
      - curl -O $build
      - chmod +x build.sh
      - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      - ./build.sh
      - rclone copy /tmp/kernel/AnyKernel3/*.zip lynx:kernel -P
