env:
    rcloneconfig: "ENCRYPTED[2aaa874ed2e5234375fc67c195e7e30c78ce131898eff50f3163102006cf60203fd01e00b040ceb5092a01a771de2024]"
    tokentl: "ENCRYPTED[278f3e180162157a66d5ecdcf54bb8a7189ae0d469d0e95018347b778a634ca8f6903a67407b27ff64ad5ca4b75a679d]"
    idtl: "ENCRYPTED[beb537072d749513bc64623e6c14b5dc34c182690c1fcff3884147aa135b64128f872e55f789dd816d7595e38b92de09]"
    script: "ENCRYPTED[!9517b186fe64cd9fbec7749c31128130ec513c637d4a923b20557a056eb408bd1db6d456e28563ff7b1c0f077c7e9d26!]"

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: 20020214/lynzx:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.config/rclone/rclone.conf
       - echo en_US UTF-8 > /etc/locale.gen
       - DEBIAN_FRONTEND=noninteractive
       - sudo apt install python3 -y
       - sudo ln -sf /usr/bin/python3 /usr/bin/python

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h

  Build-Kernel_script:
      - export LANGUAGE=en_US.UTF-8
      - export LC_ALL=en_US.UTF-8
      - export LANG=en_US.UTF-8
      - export LC_CTYPE=en_US.UTF-8
      - curl -O $script
      - chmod +x build.sh
      - ./build.sh
