env:
    rcloneconfig: "ENCRYPTED[2aaa874ed2e5234375fc67c195e7e30c78ce131898eff50f3163102006cf60203fd01e00b040ceb5092a01a771de2024]"
    tokentl: "ENCRYPTED[278f3e180162157a66d5ecdcf54bb8a7189ae0d469d0e95018347b778a634ca8f6903a67407b27ff64ad5ca4b75a679d]"
    idtl: "ENCRYPTED[beb537072d749513bc64623e6c14b5dc34c182690c1fcff3884147aa135b64128f872e55f789dd816d7595e38b92de09]"
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G
       
  Build-Env-Setup_background_script:
       - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Setup Build"
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.config/rclone/rclone.conf
       - DEBIAN_FRONTEND=noninteractive
       - sudo apt install python3 -y
       - sudo ln -sf /usr/bin/python3 /usr/bin/python
       - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
       - git config --global user.name "I-n-o-k"
       - git config --global user.email "inok.dr189@gmail.com"
       - mkdir -p /tmp/ccache
       - rclone copy lynx:nusantara-ysl-10/ccache.tar.gz /tmp -P
       - export CCACHE_DIR=/tmp/ccache
       - export CCACHE_EXEC=$(which ccache)
       - ccache --clear
       - cd /tmp
       - time tar xf ccache.tar.gz
       - cd /tmp
 
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start Sync Source"
      - cd /tmp/rom
      - rm -rf *
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/NusantaraProject-ROM/android_manifest -b 10 -g default,-device,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      # DT,VT,KT
      - git clone --depth=1 https://github.com/lynnnnzx/android_device_xiaomi_ysl -b nad-ysl-10 device/xiaomi/ysl
      - git clone --depth=1 https://github.com/lynnnnzx/android_vendor_xiaomi_ysl -b 10 vendor/xiaomi
      - git clone --depth=1 https://github.com/lynnnnzx/Logan_Ysl -b xr kernel/xiaomi/ysl
      # HALS
      - rm -rf hardware/qcom-caf/msm8996/audio
      - rm -rf hardware/qcom-caf/msm8996/display
      - rm -rf hardware/qcom-caf/msm8996/media
      - git clone --depth=1 https://github.com/Jabiyeff/android_hardware_qcom_audio -b lineage-17.1-caf-msm8996 hardware/qcom-caf/msm8996/audio
      - git clone --depth=1 https://github.com/Jabiyeff/android_hardware_qcom_display -b lineage-17.1-caf-msm8996 hardware/qcom-caf/msm8996/display
      - git clone --depth=1 https://github.com/Jabiyeff/android_hardware_qcom_media -b lineage-17.1-caf-msm8996 hardware/qcom-caf/msm8996/media
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"
      - echo "============================"
      - echo "Sync Completed!"
      - echo "============================"
 
  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build Started!"
      - ./collect.sh
#      - ./final.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd /tmp/rom/out/target/product/ysl/ && ls Nusantara*.zip) Completed!"
      - echo "============================"
      - echo "Build Completed!"
      - echo "============================"

  Upload_script:
      - echo "============================"
      - echo "Uploading the Build...."
      - echo "============================"
#      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading Build $(cd /tmp/rom/out/target/product/ysl/ && ls Nusantara*.zip) To Your Drive"
#      - rclone copy /tmp/rom/out/target/product/ysl/Nusantara*.zip lynx:ysl -P
#      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd /tmp/rom/out/target/product/ysl/ && ls Nusantara*.zip) Uploaded Successfully!"
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd /tmp
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz lynx:nusantara-ysl-10 -P
      - export CCACHE_DIR=/tmp/ccache
      - export CCACHE_EXEC=$(which ccache)
      - ccache --clear
      - echo " "
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading Ccache Successfully!"
      - echo "============================"
      - echo "Build Uploaded Successfully!"
      - echo "============================"
