env:
    rcloneconfig: "ENCRYPTED[2aaa874ed2e5234375fc67c195e7e30c78ce131898eff50f3163102006cf60203fd01e00b040ceb5092a01a771de2024]"
    tokentl: "ENCRYPTED[278f3e180162157a66d5ecdcf54bb8a7189ae0d469d0e95018347b778a634ca8f6903a67407b27ff64ad5ca4b75a679d]"
    idtl: "ENCRYPTED[beb537072d749513bc64623e6c14b5dc34c182690c1fcff3884147aa135b64128f872e55f789dd816d7595e38b92de09]"
    script: "ENCRYPTED[!d1e782c73588da10a69996df3562adf5b3b28565eb2f96ae18bb9607426f0ab5f313e13360d0eded1348e1b2f8179660!]"

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: 20020214/lynzx:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.config/rclone/rclone.conf
       - DEBIAN_FRONTEND=noninteractive
       - sudo ln -sf /usr/bin/python3 /usr/bin/python

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h

  Build-Kernel_script:
      - curl -O $script
      - chmod +x build.sh
      - ./build.sh
